name: Reusable Node Quality
run-name: Node ${{ inputs.node-version }} Quality Checks

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        required: false
        default: "20"
        type: string

permissions:
  contents: read